export type Routes = "/" | "/active" | "/completed";

export interface Payable {
  Id: number;
  TRANNUM: string | null;
  PERSON: string | null;
  OFFSET: string | null;
  ACCRUAL: string | null;
  POSTMONTH: Date | null;
  DATE: Date | null;
  DUEDATE: Date | null;
  AMOUNT: string | null;
  PROPERTY: string | null;
  ACCOUNT: string | null;
  NOTES: string | null;
  REF: string | null;
  CHECKNUM: string | null;
  DESC: string | null;
  EXPENSETYPE: string | null;
  DETAILTAXAMOUNT1: string | null;
  DETAILTAXAMOUNT2: string | null;
  DETAILTRANAMOUNT: string | null;
  DETAILVATTRANTYPEID: string | null;
  DETAILVATRATEID: string | null;
  TRANCURRENCYID: string | null;
  EXCHANGERATE: string | null;
  EXCHANGERATE2: string | null;
  AMOUNT2: string | null;
  DOCUMENTSEQUENCENUMBER: string | null;
  DISPLAYTYPE: string | null;
  Company: string | null;
  FundingEntity: string | null;
  JOB: string | null;
  CATEGORY: string | null;
  CONTRACT: string | null;
  COSTCODE: string | null;
  USERDEFINEDFIELD1: string | null;
  USERDEFINEDFIELD2: string | null;
  USERDEFINEDFIELD3: string | null;
  USERDEFINEDFIELD4: string | null;
  USERDEFINEDFIELD5: string | null;
  USERDEFINEDFIELD6: string | null;
  USERDEFINEDFIELD7: string | null;
  USERDEFINEDFIELD8: string | null;
  USERDEFINEDFIELD9: string | null;
  USERDEFINEDFIELD10: string | null;
  INTERNATIONALPAYMENTTYPE: string | null;
  WORKFLOW: string | null;
  WORKFLOWSTATUS: string | null;
  WORKFLOWSTEP: string | null;
  DETAILFIELD1: string | null;
  DETAILFIELD2: string | null;
  DETAILFIELD3: string | null;
  DETAILFIELD4: string | null;
  DETAILFIELD5: string | null;
  DETAILFIELD6: string | null;
  DETAILFIELD7: string | null;
  DETAILFIELD8: string | null;
  NOTES2: string | null;
  PONUM: string | null;
  PODETAILID: string | null;
  TRANDATE: string | null;
  RETENTION: string | null;
  ORIGINALUREF: string | null;
  CREDITMEMO: string | null;
  ADJUSTMENT: string | null;
  Labour: string | null;
  Material: string | null;
  CITBLevy: string | null;
  ManufacturingCosts: string | null;
  Travel: string | null;
  NonCisLabor: string | null;
}

export type PayableType = Payable[];

export interface CommercialEtlLeases {
  id: number;
  property_Code: string;
  lease_Term: number | null;
  lease_Code: string;
  lease_Name: string;
  lease_Type: string;
  lease_Start_Date: string | null;
  lease_End_Date: string | null;
  lease_Move_In_Date: string | null;
  sales_Category: string;
  notes: string;
  customer_Code: string;
  company_Name: string;
  separate_Amendment_Terms: number | null;
  iCS_Code: string;
  anchor: number | null;
  move_Out_Date: string | null;
  activation_date: string | null;
  possession_Date: string | null;
  occupancy_Cert_Date: string | null;
  sign_Date: string | null;
  holdover_Percentage: number | null;
  contract_End_Date: string | null;
  amendment_Description: string;
  contracted_Area: number | null;
  month_To_Month: number | null;
  base_Percentage: number | null;
  late_Fee_Calc_Type: number | null;
  grace_Period: number | null;
  dueDay: number | null;
  late_Fee_Interest_Free: number | null;
  calc_Basis_Gross: number | null;
  interest_Index: string;
  factor: number | null;
  adjustment: number | null;
  min_Threshold: number | null;
  max_Threshold: number | null;
  min_Percentage: number | null;
  max_Percentage: number | null;
  base_Percentage2: number | null;
  late_Fee_Calc_Type2: number | null;
  grace_Period2: number | null;
  max_Total_Fee_Type: number | null;
  max_Total_Fee_Percentage: number | null;
  late_Fee_Per_Day: number | null;
  max_Number_Days: number | null;
  minimum_Due: number | null;
  default_Sales_Tran_Type: string;
  vAT_Reg_Number: string;
  method_Of_Payment: number | null;
  lease_Currency: string;
  rate_Provider: string;
  rate_Type: string;
  sales_Currency: string;
  sales_Rate_Provider: string;
  sales_Rate_Type: string;
  bill_To_Customer: number | null;
  payment_Type: number | null;
  security_Deposit: number | null;
  preferred_Language: string;
  amendment_Status: number | null;
  amendment_Type: number | null;
  amendment_Sequence: number | null;
  parent_Amendment_Type: number | null;
  parent_Amendment_Sequence: number | null;
  sub_Type: number | null;
  ext_Ref_Lease_Id: string;
  ref_Property_ID: string;
  ref_Customer_ID: string;
  primaryContact_Code: string;
  billingContact_Code: string;
  ext_PrimaryContact_Code: string;
  ext_BillingContact_Code: string;
  activate: number | null;
  charge_On_Unpaid: number | null;
  days_In_Year: number | null;
  general_Info_1: string;
  general_Info_2: string;
  general_Info_3: string;
  general_Info_4: string;
  general_Info_5: string;
  general_Info_6: string;
  general_Info_7: string;
  general_Info_8: string;
  general_Info_9: string;
  general_Info_10: string;
  general_Info_11: string;
  general_Info_12: string;
  general_Info_13: string;
  general_Info_14: string;
  other_Info_1: string;
  other_Info_2: string;
  other_Info_3: string;
  other_Info_4: string;
  other_Info_5: string;
  other_Info_6: string;
  other_Info_7: string;
  other_Info_8: string;
  other_Info_9: string;
  other_Info_10: string;
  other_Info_11: string;
  other_Info_12: string;
  other_Info_13: string;
  other_Info_14: string;
  other_Info_15: string;
  other_Info_16: string;
  other_Info_17: string;
  other_Info_18: string;
  other_Info_19: string;
  other_Info_20: string;
  other_Info_21: string;
  tenant_Notes: string;
  modification_Type: number | null;
  charge_Increase_Type: number | null;
  guarantee_Required: number | null;
  isCMLLease: number | null;
  at_Risk: number | null;
  brand: string;
}

export type CommercialEtlLeasesType = CommercialEtlLeases[];
